### ISSUE TITLE
cannot load such file

### ISSUE THREAD

**Issue by roymax** [wolfg1969/rack-weixin#4]
```
{12:14}[1.9.3]~ ➭ gem install rack-weixin
Successfully installed rack-weixin-0.0.4
1 gem installed
{12:24}[1.9.3]~ ➭ irb
1.9.3p327 :001 > require  "rack-weixin"
LoadError: cannot load such file -- rack-weixin
    from /Users/roymax/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/roymax/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from (irb):1
    from /Users/roymax/.rvm/rubies/ruby-1.9.3-p327-falcon/bin/irb:16:in `<main>'
```

**Comment by wolfg1969** [comment]
rebuild gem.
